(() => {
  const KEY='control-soporte-formatos-v1';
  const templates=[
    {id:'visita-tienda',icon:'🏪',name:'Visita a tienda',fields:[['tienda','Tienda / sucursal'],['fecha','Fecha'],['encargado','Encargado de tienda'],['motivo','Motivo de visita'],['horaEntrada','Hora de entrada'],['horaSalida','Hora de salida'],['observaciones','Observaciones generales'],['firma','Firma / conformidad']]},
    {id:'incidente',icon:'⚠️',name:'Reporte de incidente',fields:[['tienda','Tienda / sucursal'],['fecha','Fecha'],['equipo','Equipo / código'],['prioridad','Prioridad'],['problema','Problema encontrado'],['accion','Acción tomada'],['pendiente','Pendiente / seguimiento'],['observaciones','Observaciones']]},
    {id:'pendientes',icon:'📋',name:'Control de pendientes',fields:[['tienda','Tienda / área'],['fecha','Fecha'],['pendiente','Pendiente'],['responsable','Responsable'],['compromiso','Fecha compromiso'],['prioridad','Prioridad'],['estado','Estado'],['seguimiento','Seguimiento / observaciones']]},
    {id:'software',icon:'💻',name:'Checklist instalación de software',fields:[['equipo','Equipo / código'],['usuario','Usuario'],['fecha','Fecha'],['so','Sistema operativo / versión'],['software','Software instalado'],['updates','Actualizaciones aplicadas'],['antivirus','Antivirus / seguridad verificado'],['pruebas','Pruebas realizadas'],['observaciones','Observaciones']]},
    {id:'equipo',icon:'🖥️',name:'Checklist instalación de equipo',fields:[['equipo','Equipo / código'],['fecha','Fecha'],['ubicacion','Ubicación'],['monitor','Monitor'],['perifericos','Teclado / mouse / periféricos'],['red','Conectividad / red'],['config','Configuración realizada'],['prueba','Prueba final'],['observaciones','Observaciones']]},
    {id:'conectividad',icon:'🌐',name:'Checklist de conectividad',fields:[['tienda','Tienda / sucursal'],['fecha','Fecha'],['internet','Internet'],['wifi','Wi-Fi'],['cableado','Cableado'],['ip','IP / DNS'],['velocidad','Prueba de velocidad'],['sistemas','Acceso a sistemas'],['observaciones','Observaciones']]},
    {id:'impresora',icon:'🖨️',name:'Checklist de impresora',fields:[['tienda','Tienda / sucursal'],['fecha','Fecha'],['equipo','Impresora / código'],['driver','Driver instalado'],['conexion','Conexión'],['prueba','Impresión de prueba'],['predeterminada','Configurada como predeterminada'],['insumos','Tóner / insumos'],['observaciones','Observaciones']]},
    {id:'mantenimiento',icon:'🔄',name:'Mantenimiento preventivo',fields:[['equipo','Equipo / código'],['fecha','Fecha'],['limpieza','Limpieza física'],['hardware','Revisión de hardware'],['updates','Actualizaciones'],['almacenamiento','Almacenamiento / disco'],['rendimiento','Rendimiento'],['seguridad','Antivirus / seguridad'],['recomendaciones','Recomendaciones']]},
    {id:'entrega',icon:'📦',name:'Entrega / recepción de equipo',fields:[['fecha','Fecha'],['equipo','Equipo / código'],['serie','Número de serie'],['accesorios','Accesorios entregados'],['condicion','Condición física'],['entrega','Responsable que entrega'],['recibe','Responsable que recibe'],['observaciones','Observaciones'],['firma','Firmas']]},
    {id:'orden',icon:'🔧',name:'Orden de trabajo de soporte',fields:[['ot','N.º de orden'],['fecha','Fecha'],['solicitante','Solicitante'],['ubicacion','Ubicación'],['problema','Problema reportado'],['diagnostico','Diagnóstico'],['solucion','Solución aplicada'],['materiales','Materiales utilizados'],['cierre','Cierre / observaciones']]},
    {id:'inspeccion',icon:'🔍',name:'Inspección general de tienda',fields:[['tienda','Tienda / sucursal'],['fecha','Fecha'],['equipos','Equipos'],['red','Red / conectividad'],['impresoras','Impresoras'],['sistemas','Sistemas'],['perifericos','Periféricos'],['estado','Estado general: OK / Revisar / Crítico'],['observaciones','Hallazgos / observaciones']]},
    {id:'acta',icon:'📝',name:'Acta de visita técnica',fields:[['tienda','Tienda / sucursal'],['fecha','Fecha'],['tecnico','Técnico'],['motivo','Motivo de visita'],['actividades','Actividades realizadas'],['hallazgos','Hallazgos'],['pendientes','Pendientes derivados'],['recomendaciones','Recomendaciones'],['conformidad','Conformidad / firma del encargado']]}
  ];
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
  const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  function injectNav(){
    if(document.querySelector('[data-formatos-nav]'))return;
    const aside=document.querySelector('aside'); if(!aside)return;
    const b=document.createElement('button');b.className='nav';b.dataset.formatosNav='1';b.innerHTML='▤ <span>Formatos</span>';b.onclick=openCenter;const logout=aside.querySelector('.logout');logout?aside.insertBefore(b,logout):aside.appendChild(b);
  }
  function openCenter(){
    const old=document.getElementById('formatos-layer');if(old)old.remove();
    const layer=document.createElement('div');layer.id='formatos-layer';layer.innerHTML=`<div class="formatos-modal"><div class="formatos-head"><div><span class="formatos-kicker">CONTROL SOPORTE</span><h2>📄 Centro de Formatos</h2><p>Plantillas editables listas para imprimir y llevar a campo.</p></div><button class="secondary" id="fmt-close">Cerrar</button></div><div class="formatos-grid">${templates.map(t=>`<article class="formato-card"><div class="formato-icon">${t.icon}</div><div><h3>${t.name}</h3><small>${t.fields.length} campos · editable · impresión tamaño carta</small></div><button data-new="${t.id}">Abrir formato</button></article>`).join('')}</div><div class="formato-history"><h3>📁 Mis formatos guardados</h3><div id="fmt-history"></div></div></div>`;
    document.body.appendChild(layer);layer.querySelector('#fmt-close').onclick=()=>layer.remove();
    layer.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>editor(templates.find(t=>t.id===b.dataset.new),null,layer));renderHistory(layer);
  }
  function editor(t,record,layer){
    const values=record?.values||{};const fields=t.fields.map(([k,l])=>`<label>${l}<textarea data-f="${k}" rows="${/observaciones|problema|diagnostico|solucion|actividades|hallazgos|pendientes|recomendaciones|seguimiento|software/i.test(k)?3:1}">${esc(values[k]||'')}</textarea></label>`).join('');
    layer.querySelector('.formatos-modal').innerHTML=`<div class="formatos-head"><div><span class="formatos-kicker">FORMATO DE CAMPO</span><h2>${t.icon} ${t.name}</h2><p>Completá los datos y guardá o imprimí.</p></div><button class="secondary" id="fmt-back">← Volver</button></div><form id="fmt-form" class="formato-editor"><div class="formato-fields">${fields}</div><div class="formato-actions"><button type="button" id="fmt-save">💾 Guardar</button><button type="button" class="secondary" id="fmt-print">🖨️ Imprimir</button></div><output id="fmt-msg"></output></form>`;
    layer.querySelector('#fmt-back').onclick=openCenter;
    layer.querySelector('#fmt-save').onclick=()=>{const v={};layer.querySelectorAll('[data-f]').forEach(x=>v[x.dataset.f]=x.value);const all=load();const item={id:record?.id||id(),template:t.id,name:t.name,values:v,updatedAt:new Date().toISOString()};const i=all.findIndex(x=>x.id===item.id);i>=0?all[i]=item:all.unshift(item);save(all);layer.querySelector('#fmt-msg').textContent='✓ Formato guardado en este dispositivo.';};
    layer.querySelector('#fmt-print').onclick=()=>{const v={};layer.querySelectorAll('[data-f]').forEach(x=>v[x.dataset.f]=x.value);printFormat(t,v);};
  }
  function printFormat(t,v){const rows=t.fields.map(([k,l])=>`<div class="p-row"><b>${esc(l)}</b><span>${esc(v[k]||'')}</span></div>`).join('');const w=window.open('','_blank');if(!w)return alert('El navegador bloqueó la ventana de impresión. Permití ventanas emergentes para este sitio.');w.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${esc(t.name)}</title><style>@page{size:letter;margin:14mm}body{font-family:Arial,sans-serif;color:#172033;font-size:11px}header{border-bottom:2px solid #173f76;padding-bottom:10px;margin-bottom:14px}h1{margin:0;font-size:20px}p{margin:4px 0;color:#667085}.p-row{border:1px solid #cbd5e1;min-height:30px;margin:7px 0;display:grid;grid-template-columns:31% 69%}.p-row b{background:#f1f5f9;padding:7px}.p-row span{padding:7px;white-space:pre-wrap}.sign{margin-top:35px;display:flex;gap:70px}.line{border-top:1px solid #333;padding-top:5px;width:210px;text-align:center}@media print{button{display:none}}</style></head><body><header><h1>CONTROL SOPORTE · ITE</h1><p>${esc(t.name)} · Fecha de impresión: ${new Date().toLocaleString('es-HN')}</p></header>${rows}<div class="sign"><div class="line">Técnico / responsable</div><div class="line">Encargado de tienda</div></div><script>window.onload=()=>window.print();</script></body></html>`);w.document.close();}
  function renderHistory(layer){const box=layer.querySelector('#fmt-history'),all=load();if(!all.length){box.innerHTML='<p class="fmt-empty">Todavía no hay formatos guardados en este dispositivo.</p>';return}box.innerHTML=all.slice(0,15).map(r=>`<div class="fmt-history-row"><span><b>${esc(r.name)}</b><small>${new Date(r.updatedAt).toLocaleString('es-HN')}</small></span><div><button data-edit="${r.id}">Editar</button><button class="secondary" data-print="${r.id}">Imprimir</button><button class="danger" data-del="${r.id}">Eliminar</button></div></div>`).join('');box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const r=load().find(x=>x.id===b.dataset.edit);const t=templates.find(x=>x.id===r.template);editor(t,r,layer)});box.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>{const r=load().find(x=>x.id===b.dataset.print);printFormat(templates.find(x=>x.id===r.template),r.values)});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar este formato guardado?')){save(load().filter(x=>x.id!==b.dataset.del));renderHistory(layer)}})}
  new MutationObserver(injectNav).observe(document.body,{childList:true,subtree:true});setInterval(injectNav,1000);injectNav();
})();