import { initializeApp, getApps, getApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, collection, addDoc, getDocs, doc, updateDoc, deleteDoc, query, where, Timestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { firebaseConfig } from './config.js';

const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const css=document.createElement('style');css.textContent=`#cs-r-fab{position:fixed;right:18px;bottom:18px;z-index:9998;border:0;border-radius:999px;background:#073b7a;color:#fff;padding:13px 17px;font-weight:800;box-shadow:0 10px 25px #0003;cursor:pointer}#cs-r-panel{position:fixed;right:18px;bottom:72px;width:min(410px,calc(100vw - 28px));max-height:82vh;overflow:auto;z-index:9999;background:#fff;border:1px solid #dbe3ef;border-radius:18px;box-shadow:0 18px 50px #0003;padding:18px;color:#172033}#cs-r-panel[hidden],#cs-r-fab[hidden]{display:none}.crh{display:flex;justify-content:space-between;align-items:center}.crh h3{margin:0}.crf{display:grid;gap:9px}.crf input,.crf textarea,.crf select{width:100%;box-sizing:border-box;border:1px solid #cbd6e4;border-radius:10px;padding:10px;font:inherit}.crf textarea{min-height:55px}.crrow{display:grid;grid-template-columns:1fr 1fr;gap:9px}.crb{border:0;border-radius:10px;padding:11px;background:#073b7a;color:#fff;font-weight:800;cursor:pointer}.crs{background:#eef3f9;color:#17324d}.crnote{font-size:12px;color:#667085}.crlist{display:grid;gap:8px;margin-top:15px}.crcard{border:1px solid #e0e6ef;border-radius:12px;padding:11px}.crcard small{color:#667085}.cra{display:flex;gap:7px;margin-top:8px}.cra button{border:0;border-radius:8px;padding:7px 9px}.cerr{color:#a61b1b;font-size:12px}.cok{color:#175c37;font-size:12px}.crmail{font-size:12px;color:#475467;margin-top:3px}@media(max-width:520px){#cs-r-fab{right:12px;bottom:12px}#cs-r-panel{right:12px;bottom:64px}}`;document.head.appendChild(css);
const fab=document.createElement('button');fab.id='cs-r-fab';fab.type='button';fab.textContent='🔔 Recordatorios';fab.hidden=true;
const panel=document.createElement('section');panel.id='cs-r-panel';panel.hidden=true;panel.innerHTML=`<div class="crh"><h3>🔔 Mis recordatorios</h3><button id="cr-close" type="button">×</button></div><div class="crf"><input id="cr-title" placeholder="¿Qué querés recordar?" maxlength="120"><textarea id="cr-note" placeholder="Detalle opcional" maxlength="300"></textarea><input id="cr-email" type="email" placeholder="Correo donde recibir el recordatorio" autocomplete="email" maxlength="160"><div class="crrow"><input id="cr-date" type="date"><input id="cr-time" type="time" value="08:00"></div><div class="crrow"><select id="cr-repeat"><option value="none">Una vez</option><option value="daily">Todos los días</option><option value="weekly">Cada semana</option></select><button id="cr-save" class="crb" type="button">Guardar</button></div><div id="cr-status"></div><p class="crnote">📧 El recordatorio llegará al correo indicado. El envío automático se procesa cada pocos minutos.</p></div><div id="cr-list" class="crlist"></div>`;document.body.append(fab,panel);
const $=id=>document.getElementById(id);let user=null,items=[];$('cr-date').value=new Date().toISOString().slice(0,10);
const esc=v=>String(v||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const status=(s,e=false)=>{$('cr-status').textContent=s;$('cr-status').className=e?'cerr':'cok'};
async function load(){if(!user)return;try{const s=await getDocs(query(collection(db,'reminders'),where('uid','==',user.uid)));items=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`));render();}catch(e){console.error(e);status('No se pudieron cargar los recordatorios. Publicá las reglas de Firestore para habilitarlos.',true);}}
function render(){$('cr-list').innerHTML=items.length?items.map(r=>`<article class="crcard"><strong>${esc(r.title)}</strong>${r.note?`<br><small>${esc(r.note)}</small>`:''}<div class="crmail">📧 ${esc(r.email||'Sin correo')}</div><br><small>${r.date} · ${r.time} · ${{none:'Una vez',daily:'Diario',weekly:'Semanal'}[r.repeat]||'Una vez'}</small><div class="cra"><button data-t="${r.id}">${r.enabled===false?'Activar':'Pausar'}</button><button data-d="${r.id}">Eliminar</button></div></article>`).join(''):'<div class="crnote">No tenés recordatorios todavía.</div>';}
async function save(){const title=$('cr-title').value.trim(),date=$('cr-date').value,time=$('cr-time').value,repeat=$('cr-repeat').value,note=$('cr-note').value.trim(),email=$('cr-email').value.trim();if(!user||!title||!date||!time||!email)return status('Completá título, correo, fecha y hora.',true);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return status('Escribí un correo válido.',true);const nextAt=new Date(`${date}T${time}:00`);try{await addDoc(collection(db,'reminders'),{uid:user.uid,title,note,email,date,time,repeat,enabled:true,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,nextAt:Timestamp.fromDate(nextAt),createdAt:Timestamp.now()});$('cr-title').value='';$('cr-note').value='';$('cr-email').value=user.email||'';status('✅ Recordatorio guardado.');load();}catch(e){console.error(e);status('No se pudo guardar. Publicá las reglas de Firestore para habilitar recordatorios.',true);}}
async function toggle(id){const r=items.find(x=>x.id===id);if(r)try{await updateDoc(doc(db,'reminders',id),{enabled:r.enabled===false});load();}catch(e){console.error(e);status('No se pudo cambiar el estado del recordatorio.',true);}}
async function del(id){if(confirm('¿Eliminar este recordatorio?'))try{await deleteDoc(doc(db,'reminders',id));load();}catch(e){console.error(e);status('No se pudo eliminar el recordatorio.',true);}}
fab.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden){if(user&&!$('cr-email').value)$('cr-email').value=user.email||'';load()}};$('cr-close').onclick=()=>panel.hidden=true;$('cr-save').onclick=save;$('cr-list').onclick=e=>{if(e.target.dataset.t)toggle(e.target.dataset.t);if(e.target.dataset.d)del(e.target.dataset.d)};
onAuthStateChanged(auth,u=>{user=u;fab.hidden=!u;if(u){$('cr-email').value=u.email||'';load()}});
